#!/bin/sh
##
## git-heads -- show unmerged branches with git-log(1)
##
## Usage: git-heads [--all | --local | --remote] [--branches] [(--contains | --merged | --no-merged) [<commit>]] [git-log-OPTION]...
## Usage: git-heads [--all | --local | --remote] [--heads] [git-log-OPTION]...
## Options:
##     -a, --all                 list all branches
##     -l, --local               only local branches
##     -r, --remote              only remote branches
##     -b, --branch, --branches  list branches
##     -h, --head, --heads       only branches without children

git_exec_path="$(git --exec-path)"

ifs="$IFS"
IFS=":"
for dir in $git_exec_path; do
    [ -f "$dir/git-sh-setup" -a -r "$dir/git-sh-setup" ] \
            && . "$dir/git-sh-setup" && break
done || {
    echo "fatal: unable to find and source git-sh-setup in" \
         "GIT_EXEC_PATH=$git_exec_path" >&2
    exit 1
}
IFS="$ifs"

require_work_tree

if git config --get-colorbool color.log; then
    color_auto="always"
else
    color_auto="never"
fi
git_branch_args="--color=never"
git_branch_scope=""
git_log_args="--color=$color_auto -n 1"
heads="true"

while [ "$#" -gt 0 ]; do
    case "$1" in
        (-a|--all)
            git_branch_scope="-a"
            shift
            ;;
        (-l|--local)
            git_branch_scope=""
            shift
            ;;
        (-r|--remote)
            git_branch_scope="-r"
            shift
            ;;
        (-b|--branch|--branches)
            heads="false"
            shift
            ;;
        (-h|--head|--heads)
            heads="true"
            shift
            ;;
        (--contains|--merged|--no-merged)
            if [ -n "$2" -a "$2" = "${2#-}" ]; then
                git_branch_args="$git_branch_args '$1=$2'"
                shift 2
            else
                git_branch_args="$git_branch_args '$1=HEAD'"
                shift
            fi
            heads="false"
            ;;
        (--contains=*|--merged=*|--no-merged=*)
            git_branch_args="$git_branch_args '$1'"
            heads="false"
            shift
            ;;
        (--color)
            case "$2" in
                (auto)
                    git_log_args="$git_log_args --color=$color_auto"
                    shift 2
                    ;;
                (always|never)
                    git_log_args="$git_log_args --color=$2"
                    shift 2
                    ;;
                (*)
                    git_log_args="$git_log_args --color=always"
                    shift
                    ;;
            esac
            ;;
        (--color=auto)
            git_log_args="$git_log_args --color=$color_auto"
            shift
            ;;
        (--color=*)
            git_log_args="$git_log_args '$1'"
            shift
            ;;
        (--no-color)
            git_log_args="$git_log_args --color=never"
            shift
            ;;
        (*)
            git_log_args="$git_log_args '$1'"
            shift
            ;;
    esac
done

branches() {
    local LANG=C  ## speed up sort and uniq a bit

    git branch --color=never $git_branch_scope "$@" \
            | sed '/^\* (no branch)$\| -> /d;s/^..//' \
            | xargs git rev-parse --revs-only | sort -u
}

heads() {
    local LANG=C                      ## speed up sort and uniq a bit
    local refs="$(branches | wc -l)"

    branches | while read -r ref; do
        branches --no-merged="$ref" | { echo "$ref"; cat; } | sort -u
    done | sort | uniq -c | sed -n "s/^[[:space:]]*$refs[[:space:]]*//p"
}

if "$heads"; then
    heads
else
    eval branches $git_branch_args
fi | while read -r ref; do
    echo
    eval git log $git_log_args "'$ref'" || exit 1
done | tail -n +2 | git_pager

